## Netlify configuration for Bihar Assembly 3D visualization
[build]
	command = "npm run build"
	publish = "build"
	environment = { NODE_VERSION = "18" }

## Single Page App fallback
[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[dev]
	command = "npm start"
	port = 3000
	autoLaunch = false
